security:
    encoders:
        FOS\UserBundle\Model\UserInterface:
            algorithm: bcrypt
            cost: 12

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        acp:
            pattern:  ^/acp/
            provider: fos_userbundle
            form_login:
                csrf_provider:       security.csrf.token_manager
                check_path:          acp.login_check
                login_path:          acp.login
                default_target_path: acp.home
            logout:
                path:   acp.logout
                target: acp.login
            anonymous: ~
        default:
            anonymous: ~
    access_control:
        - { path: ^/acp/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/acp/, roles: ROLE_ACP_TWOMARTENS.CORE_ACCESS }
